### ISSUE TITLE
Reaction execution time resolution

### ISSUE THREAD

**Issue by akihitoiwai0912** [densoGSR/lf_test#1]
### Test code
- [Single_Thread.lf](https://github.com/densoGSR/lf_test/blob/main/Dashboard/src/Single_Thread.lf)

### Reaction execution time view

In the WCET view and Maxmum lag view, up to the microsec order is displayed, for example, 10.3 ms is displayed, but when checked in the reaction execution time view, duration 10 ms is displayed at mouseover. The minimum display unit may be 1 ms. Similarly, it is good to display up to the microsec order as well as other factor for example idle time.

![image](https://github.com/user-attachments/assets/fbc923cc-6360-4a5d-9ae2-947e1b75f393)

### Reaction WCET view
![スクリーンショット_22-8-2024_103229_localhost](https://github.com/user-attachments/assets/34c619f3-8493-4b73-bb09-45d5595393fc)

### Maxmum Lag view
![スクリーンショット_22-8-2024_10335_localhost](https://github.com/user-attachments/assets/49ba987b-3a79-46b7-8250-6de78ef73fca)

**Comment by elgeeko1** [comment]
The user interface component this references is the `hover tooltip` in Grafana. Some (but not all) panel types display a value of a measurement on mouse hover. The reaction execution measurement utilizes the Grafana "State Timeline" panel, which automatically determines the durations between state transitions. Unfortunately resolution of the `hover tooltip` does not appear to be configurable for this panel. We would need to investigate workarounds or alternative solutions.

It would be nice to have a higher resolution in the hover tooltip. You can measure the duration more accurately by zooming in and using cursors at the start and endpoints. It's cumbersome but will work.

**Comment by akihitoiwai0912** [comment]
Thank you for your kind explaination! I could understand the mechanism. But I appreciate your further investigation to improve that. In addition, it would be helpful if you could demonstrate how to increase the resolution of hover tooltips at our next meeting.

**Comment by elgeeko1** [comment]
For panels that support `hover tooltip`, the default resolution will be the resolution of the x-axis. This default may be overridden specifically for the `hover tooltip` parameter.

The panel type we used for the reaction execution time diagram, the State Transition panel, computes the duration of the state change and shows the computed value on hover, though it is not the value of the x-axis which is physical timestamps. Unfortunately it appears this panel does not support changing the resolution of its hover tooltip, so there is not a change we can demonstrate for this.
