### ISSUE TITLE
Displayed for each reaction in the reaction execution view

### ISSUE THREAD

**Issue by akihitoiwai0912** [densoGSR/lf_test#2]
### Test code
- [Single_Thread.lf](https://github.com/densoGSR/lf_test/blob/main/Dashboard/src/Single_Thread.lf)

When testing the execution order of reactions, it is better if they are displayed for each reaction rather than for each reactor.

![image](https://github.com/user-attachments/assets/f43b539a-e6b1-4221-8ddf-8c5ba76bbfcd)

![image](https://github.com/user-attachments/assets/2f1cf442-cba6-4423-a1b4-df51ec03489d)

**Comment by elgeeko1** [comment]
Agreed, we'll look into this and will update with our progress.
